# Organizer Guide {-}

The inaugural AnVIL Community Conference 2024 CoFests! will take place on November 12-13, 2024 in Cold Spring Harbor, NY.
This event is a key event for professionals in the genomics community interested in biomedical and genomic cloud computing and takes place immediately before the sixth meeting on [Biological Data Science](https://meetings.cshl.edu/meetings.aspx?meet=DATA&year=24).

- https://anvilproject.org/events/anvil2024-community-conference

## CoFests! Goals {- .unlisted}

- Build an inclusive community that is supportive of newcomers
- Contribute to [open science](https://en.wikipedia.org/wiki/Open_science)
- Produce a final product that accomplishes one of the following for a topic
  - Makes useful forward progress
  - Identifies opportunities and boundaries or limitations

## Logistics {- .unlisted}

- 3 Parallel tracks, 5+ hours across Nov 12/13
  - Scalable Machine Learning and Data Science
  - Polygenic Risk Score Analysis
  - Wrap a Tool (+ Intro AnVIL/WDL)
- Scientific Lead and AnVIL Outreach co-Lead for support
- We expect 4-10 participants per track

Prior to the CoFests, the scientific and AnVIL Outreach co-Leads will work together to enumerate some ideas for final products and post them publicly in this book.

::: {.notice}
The AnVIL Outreach co-Lead will help add content to this guide, onboard newer AnVIL users to the platform, and provide guidance on the final product / report out.
:::

## Final Product / Report Out {-}

The final product of CoFests doesn't need to be code! These Collaboration Fests can support story-boarding future work or development of documentation or training materials. If it's something that will help the community and make progress on an AnVIL associated topic and there's sufficient interest, the idea is game! [As Galaxy phrased it for their CoFests:](https://galaxyproject.org/events/gcc2023/cofest/#goals)

> [The goal of collaboration fests is to expand the ecosystem] Not just the code, but the whole ecosystem. That includes training, tools, best practice workflows, documentation, test cases, translations, infrastructure, and yes, even code.  

::: {.notice}
It helps us a lot if you can fill out some basic [Report Out details](https://docs.google.com/document/d/1wLK88p_tY6L-a8IF5dIe7gmDlJC1RxeU8_pm1ClU2IE/edit?usp=sharing). At the end of Day 2, your track will **share a final report during the CoFest Recap Session**!  
:::

## Example Schedule for a Track {- .unlisted}

### Day 1 (2.5 hours) {-}

| Task                      | Time & Lead |
|:-------------------------:|:-----------:|
| **Problem statement.** Provide background info on the track's overall topic and may include a brief summary of the pre-worked collaboration ideas. | 20-30 minutes (Scientific Lead) |
| **Brainstorming.** What project will the track tackle? Focus on understanding the participant backgrounds and skills and matching those with track ideas and actionable tasks to accomplish the goal. | 15-30 minutes (Both) |
| **Onboarding.** Handle billing accounts and other logistics necessary to accomplish the work. | 30-60 minutes (AnVIL Outreach co-Lead) | 
| **Work-regroup, work-regroup.** Formal collaboration work time left before dinner. (Groups may choose to work together informally after dinner too) | 30-60 minutes (N/A) |

### Day 2 (3 hours) {-}

| Task                      | Time & Lead |
|:-------------------------:|:------------|
| **Work-regroup, work-regroup.** Formal collaboration work time (with a coffee break). | 2-2.5 hours (N/A) |
| **Construct a "report out".** The report out may be a Google doc, Google slides, a GitHub repository, [a website](https://github.com/jhudsl/OTTR_Template_Website), an [OTTR book](https://github.com/jhudsl/OTTR_Template), etc. | 30-60 minutes (AnVIL Outreach co-Lead) |
